#!/usr/bin/env node
// Generates supabase/seed-demo.sql from public/demo-data.js so the live portal has the same
// demo partner (Mike's Plumbing) for sales calls. Run:  node scripts/make-seed.js
const fs = require("fs");
const path = require("path");
require(path.join(__dirname, "..", "public", "demo-data.js"));
const D = globalThis.LEADHIVE_DEMO.build(new Date());
const q = (v) => (v == null ? "null" : "'" + String(v).replace(/'/g, "''") + "'");
const j = (v) => "'" + JSON.stringify(v).replace(/'/g, "''") + "'::jsonb";
const mike = D.clients[0];
const lines = [];
lines.push("-- Demo partner for sales calls: Mike's Plumbing (demo@leadhivenz.com).");
lines.push("-- Generated by scripts/make-seed.js on " + new Date().toISOString().slice(0, 10) + ". Safe to re-run.");
lines.push("begin;");
lines.push(`delete from public.clients where id = ${q(mike.id)};`);
lines.push(`insert into public.clients (id, business_name, initials, contact_name, email, phone, niche, region, country, timezone, package_name, monthly_fee, lead_target_min, lead_target_max, started_on, billing_day, show_ad_spend, avg_job_value, active) values (${[mike.id, mike.business_name, mike.initials, mike.contact_name, mike.email, mike.phone, mike.niche, mike.region, mike.country, mike.timezone, mike.package_name, mike.monthly_fee, mike.lead_target_min, mike.lead_target_max, mike.started_on, mike.billing_day, mike.show_ad_spend, mike.avg_job_value, mike.active].map(q).join(", ")});`);
for (const m of D.months.filter((x) => x.client_id === mike.id)) {
  lines.push(`insert into public.months (id, client_id, ym, status, summary, points, published_at) values (${q(m.id)}, ${q(m.client_id)}, ${q(m.ym)}, ${q(m.status)}, ${q(m.summary)}, ${j(m.points)}, ${q(m.published_at)});`);
  lines.push(`insert into public.month_private (month_id, ad_spend) values (${q(m.id)}, ${m.ad_spend || 0});`);
}
for (const c of D.calls.filter((x) => x.client_id === mike.id)) {
  lines.push(`insert into public.calls (client_id, ym, called_at, caller_number, duration_sec, outcome, tracking_number, source, campaign, keyword, city, recording_url, nimbata_call_id, admin_note, summary, estimated_value, client_status, job_value, client_note) values (${[c.client_id, c.ym, c.called_at, c.caller_number, c.duration_sec, c.outcome, c.tracking_number, c.source, c.campaign, c.keyword, c.city, null, c.nimbata_call_id, c.admin_note, c.summary || "", c.estimated_value, c.client_status, c.job_value, c.client_note].map(q).join(", ")});`);
}
for (const e of D.enquiries.filter((x) => x.client_id === mike.id)) {
  lines.push(`insert into public.enquiries (client_id, ym, received_at, name, phone, suburb, message, is_urgent, page, source, client_status, job_value, client_note) values (${[e.client_id, e.ym, e.received_at, e.name, e.phone, e.suburb, e.message, e.is_urgent, e.page, e.source, e.client_status, e.job_value, e.client_note].map(q).join(", ")});`);
}
lines.push("commit;");
lines.push("-- Then create the demo login from Admin → Mike's Plumbing → Settings & login (email demo@leadhivenz.com).");
const out = path.join(__dirname, "..", "supabase", "seed-demo.sql");
fs.writeFileSync(out, lines.join("\n") + "\n");
console.log("wrote", out, lines.length, "lines");
